### ISSUE TITLE
Support links surrounded by angle brackets

### ISSUE THREAD

**Issue by miralize** [Teamwork/github-sync#12] opened 2020-09-10 00:25 UTC
I'm using [markdownlint](https://github.com/DavidAnson/markdownlint) to lint my `.md` files. Using the default rules out of the box they autofix links to be surrounded by angle brackets i.e.

```
<https://github.com/Teamwork/github-sync>
```

This causes problems for some reason & I think this has trouble parsing the url.

The rule is outlined [here](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034) and the original markdown spec has a section with more info https://daringfireball.net/projects/markdown/syntax#link

**Comment by miguelbemartin** [comment] 2020-09-10 17:58
Hey @miralize, thanks for taking the time to open an issue. 

I am trying to reproduce the case but I don't understand exactly what the issue is. I did a test using the angle brackets and it works correctly. Could you give me an example when the process is failing and what the expected behaviour is?

**Comment by miguelbemartin** [comment] 2020-09-16 21:06
Closing this issue. I can't reproduce. Feel free to open again if it happens again.

**Closed by miguelbemartin** 2020-09-16 21:06 UTC
Labels: enhancement, question
